version: '3.3'
services:
  registry:
    image: jovaniac/registry-microservice:0.0.1-snapshot
    ports:
      - 8761:8761
  gateway:
    image: jovaniac/gateway-microservice:0.0.1-snapshot
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    ports:
      - 8765:8765
    links:
      - registry 
  postgres:
    build: servicesData/postgresdb/
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5433:5432
    volumes:
      - ./blockstorage/postgres:/var/lib/postgresql/dataz
  